name: osmi-bench
sbatch:
  mode: h
  dir: localscratch

experiment:
  card_name: a100
  gpu_count: 1
  cpu_num: 6
  mem: "32GB"
  # repeat: "1"
  # repeat: "1,2,3,4,5"
  batch_size: "16,48,96"
  batches: "32,64,128"
  model: "small_lstm, large_lstm"

system:
  time: "00:30:00"
  host: "rivanna"
  python: "3.10.8" #fix
  num_cpus: 1
  partition: "bii-gpu"
  allocation: bii_dsc_community
  constraint: ""

submission:
  benchmark: osmi
  submitter: Gregor von Laszewski
  email: laszewski@gmail.com
  org: University of Virginia
  division: closed
  version: mlcommons-osmi-v1.0
  github_commit_version: TBD
  status: completed
  platform: rivanna

# run:
# #   filesystem: "/localscratch/{os.USER}"
#   # workdir: "/localscratch/{os.USER}/mlcommons/{experiment.TFTTransformerepochs}/{experiment.repeat}"
#   venvpath: "$HOME/mlcommons-work/python"
#   datadir: data
#   branch: 'main'
#   # allocation: ds6011-sp22-002
#   # allocation: bii_dsc
